### ISSUE TITLE
_autolayoutTrace causes Appstore submission failure

### ISSUE THREAD

**Issue by amleszk** [floriankugler/FLKAutoLayout#29]
When submitting to the appstore, the error is "The app references non-public selectors in Payload"

**Comment by amleszk** [comment]
Already fixed :+1:

**Comment by ferrous777** [comment]
This issue does not appear to be fixed. I'm on version 1.0.0

Non-public API usage:

The app references non-public selectors in Frameworks/FLKAutoLayout.framework/FLKAutoLayout: _autolayoutTrace, asciiArtDescription
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

**Comment by orta** [comment]
Sounds like you're submitting a non-debug build, as it's ifdef'd behind a `DEBUG` flag.

**Comment by ferrous777** [comment]
Okay, thanks.
