### ISSUE TITLE
nil predicate not equal to @"0"

### ISSUE THREAD

**Issue by Ahti** [floriankugler/FLKAutoLayout#3]
the changes to FLKAutoLayout/UIView+FLKAutoLayout.m in commit c8f5ec0 should be reverted, imho.

If you pass a nil predicate into any of the methods whose behaviour is changed there, it won't act like you actually passed @"0", but will actually not add any constraints at all, which is inconsistent with all the other methods.

**Comment by orta** [comment]
For working with Swift, I've opted to migrate the predicates to be `_Nonnull` meaning this conversation - we found when working with FLK that we also assumed that nil would mean don't set this, and had to teach that to most developers on the team. Making it not null means the API has a lower barrier to entry 👍
