### ISSUE TITLE
XCode 6.3 beta 2 warning

### ISSUE THREAD

**Issue by danielgomezrico** [floriankugler/FLKAutoLayout#30]
I have this warning in this file `UIView+FLKAutoLayoutDebug.m`

![screen shot 2015-03-19 at 1 58 40 pm](https://cloud.githubusercontent.com/assets/76348/6738461/3ae696b2-ce40-11e4-82ef-c9e82adc6319.png)

**Comment by cjimenezpacho** [comment]
Same here, but in XCode 6.2

**Comment by orta** [comment]
This should be fixed in #45
