### ISSUE TITLE
make `chainViews:usingBlock:` public, add methods for aligning the centers of an array of views.

### ISSUE THREAD

**Issue by 1aurabrown** [floriankugler/FLKAutoLayout#38]
I think it would be nice if  `chainViews:usingBlock:` was available to use anywhere with an arbitrary block. What do you think?

In particular, I'd like to have something similar to `alignLeadingEdgesOfViews:` that would align the centers of views in either or both axes. I often have views of different widths and would like to ensure that their centerX is aligned.

Photoshop has this:
![screen shot 2015-07-10 at 4 56 51 pm](https://cloud.githubusercontent.com/assets/3171662/8628922/cf51313a-2724-11e5-92f5-1eb49171e92a.png)

![untitled-1](https://cloud.githubusercontent.com/assets/3171662/8628960/039a0cdc-2725-11e5-8a7c-33a0b68dacdc.jpg) ![untitled-2](https://cloud.githubusercontent.com/assets/3171662/8628962/054d3784-2725-11e5-9410-d66f65db567f.jpg)

Equivalent:
```
+ (NSArray*)alignCenterXOfViews:(NSArray*)views {
    return [self chainViews:views usingBlock:^NSArray*(UIView* view1, UIView* view2) {
        return [view2 alignCenterXWithView:view1 predicate:nil];
    }];
}
```

I'm happy to PR these particular center-alignment chaining methods, but it would be nice if the underlying `chainViews` method was available, too.

**Comment by orta** [comment]
Let's skip this for now, we've managed to survive without the API, and no-one else seems to be +1ing it.
