### ISSUE TITLE
Constraint Methods Should Accept Format Strings

### ISSUE THREAD

**Issue by rhgills** [floriankugler/FLKAutoLayout#6]
If I have certain UI constants, I should be able to pass those directly to the constraint methods as a predicate with printf-style specifiers.

Currently, you need:

    {
      [view alignTopEdgeWithView:superview 
                       predicate:[NSString stringWithFormat:@"%@", [settings paddingFromTop]]];
    }

Instead of the simpler:

    {
      [view alignTopEdgeWithView:superview predicate:@"%@", [settings paddingFromTop]];
    }

**Comment by orta** [comment]
This is a good idea IMO, and something we've worked around it a lot. 

Though, with swift now supporting interpolated strings I think it's less of an issue. I'm going to close for prosperity.
